### ISSUE TITLE
Build failure on Ubuntu 20.04 and Foxy when running "colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release"

### ISSUE THREAD

**Issue by shyamkris** [open-rmf/rmf#281]
## Bug report
Getting the following error while building the RMF source using "colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release"

--- stderr: nlohmann_json_schema_validator_vendor
In file included from /home/admin/rmf_foxy_ws/build/nlohmann_json_schema_validator_vendor/nlohmann_json_schema_validator-1063c9adbafc25f5a14bae15c3babdb039de86c6-prefix/src/nlohmann_json_schema_validator-1063c9adbafc25f5a14bae15c3babdb039de86c6/src/json-validator.cpp:9:
/home/admin/rmf_foxy_ws/build/nlohmann_json_schema_validator_vendor/nlohmann_json_schema_validator-1063c9adbafc25f5a14bae15c3babdb039de86c6-prefix/src/nlohmann_json_schema_validator-1063c9adbafc25f5a14bae15c3babdb039de86c6/src/nlohmann/json-schema.hpp:28:4: error: #error "Please use this library with NLohmann's JSON version 3.8.0 or higher"
   28 | #  error "Please use this library with NLohmann's JSON version 3.8.0 or higher"
      |    ^~~~~
### Required information:

- Operating system and version:
  - Ubuntu 20.04
- OpenRMF installation type:
  -21.09 for Foxy - https://github.com/open-rmf/rmf 
- OpenRMF version or commit hash
  - 21.09
- ROS distribution and version:
  - ROS2 Foxy
- ROS installation type:
  - https://docs.ros.org/en/foxy/Installation/Ubuntu-Install-Debians.html 
- Package or library, if applicable:
  - Package

### Description of the bug
--- stderr: nlohmann_json_schema_validator_vendor
In file included from /home/admin/rmf_foxy_ws/build/nlohmann_json_schema_validator_vendor/nlohmann_json_schema_validator-1063c9adbafc25f5a14bae15c3babdb039de86c6-prefix/src/nlohmann_json_schema_validator-1063c9adbafc25f5a14bae15c3babdb039de86c6/src/json-validator.cpp:9:
/home/admin/rmf_foxy_ws/build/nlohmann_json_schema_validator_vendor/nlohmann_json_schema_validator-1063c9adbafc25f5a14bae15c3babdb039de86c6-prefix/src/nlohmann_json_schema_validator-1063c9adbafc25f5a14bae15c3babdb039de86c6/src/nlohmann/json-schema.hpp:28:4: error: #error "Please use this library with NLohmann's JSON version 3.8.0 or higher"
   28 | #  error "Please use this library with NLohmann's JSON version 3.8.0 or higher"
      |    ^~~~~

### Steps to reproduce the bug

<!-- Detailed instructions on how to reliably reproduce the bug, e.g.
Follow the RMF installation in readme. https://github.com/open-rmf/rmf/tree/release/21.09 

### Expected behavior
Build should be successful

### Actual behavior
Build fails.

**Comment by Yadunund** [comment]
We haven't been actively maintaining support for source builds on `Ubuntu 20.04` + `Foxy`. But other users have reported a similar issue and work around [here](https://github.com/open-rmf/nlohmann_json_schema_validator_vendor/issues/11#issuecomment-1318107790). But I think the issue was encountered with the latest `main` and not the `21.09` tagged version as you have documented in your description.

**Comment by shyamkris** [comment]
I faced the same issue in Galactic as well. And yes, I used the main branch. I mentioned 21.09 since the readme file said Install instructions of 21.09. Could you please explain what's the fix?

**Comment by shyamkris** [comment]
I followed the installed instructions from here https://github.com/open-rmf/rmf/tree/release/21.09 
Is this main branch?

**Comment by santoshbalaji** [comment]
i had faced similar issue when installing rmf on galactic version. From the error printed above it reports nlohmann's json library needs to be of version 3.8.0 and higher. 
1) First use apt list | grep "nlohmann" and check what version of binary is already installed in the PC
2) If it is lower than 3.8.0 remove the old package 
3) Clone the latest version of json library from github (git clone git@github.com:nlohmann/json.git)
4) Installing the json library from source
cd json_pkg_name 
mkdir build
cd build
cmake ..
make
sudo make install
5) Try colcon build again 

See if this helps !!!!!

**Comment by aaronchongth** [comment]
See https://github.com/open-rmf/rmf/issues/322 for galactic build issues
